const Portfolio_data = [
  {
    id: 1,
    category: "WEB APPLICATION",
    title: "Budget App",
    image: "/images/Budgets.png",
    demo: "https://budget-appdemos.netlify.app/",
    github: "https://github.com/elliottcsipkes/budget-app",
    desc: "",
  },
  {
    id: 2,
    category: "WEB APPLICATION",
    title: "CryptoSearch",
    image: "/images/CryptoApp.png",
    demo: "https://cryptosearch-demo.netlify.app/",
    github: "https://github.com/elliottcsipkes/crypto-api-app",
    desc: "",
  },
  {
    id: 3,
    category: "WEB APPLICATION",
    title: "Pokedex",
    image: "/images/pokeapp.png",
    demo: "https://pokemon-pokedex-demo.netlify.app/",
    github: "https://github.com/elliottcsipkes/pokemon-app",
    desc: "",
  },
  {
    id: 4,
    category: "WEB APPLICATION",
    title: "Notes App",
    image: "./image/portfolio-04.jpg",
    demo: "",
    github: "https://github.com/elliottcsipkes/notes-app",
    desc: "",
  },
  {
    id: 5,
    category: "WEB APPLICATION",
    title: "Moviebase",
    image: "./image/portfolio-05.jpg",
    demo: "",
    github: "https://github.com/elliottcsipkes/movie-database-app",
    desc: "",
  },
  {
    id: 6,
    category: "PORTFOLIO WEBSITE",
    title: "Personal Portfolio",
    image: "/images/portfolio.png",
    demo: "",
    github: "https://github.com/elliottcsipkes/dev-porfolio",
    desc: "",
  },
];
export default Portfolio_data;
