const Portfolio_data = [
  {
    id: 1,
    category: "WEB APPLICATION",
    title: "Budgets - Organize a Budget by Setting Limits Recording Spending",
    image: "/images/Budgets.png",
    demo: "https://budget-appdemos.netlify.app/",
    github: "https://github.com/elliottcsipkes/budget-app",
    desc: "Styled entirely with Bootstrap and React Bootstrap components, this budgets app allows the user to set multiple budget categories and then add expenses to each. As expenses increase, the progress bar fills and may change color to indicate how close the user is to hitting the maximum alotted spending. Expenses can also be added without being specifically added to a budget and will be stored in the uncategorized display.",
  },
  {
    id: 2,
    category: "WEB APPLICATION",
    title: "CryptoSearch - Find Market Information on Cryptocurrencies",
    image: "/images/CryptoApp.png",
    demo: "https://cryptosearch-demo.netlify.app/",
    github: "https://github.com/elliottcsipkes/crypto-api-app",
    desc: "",
  },
  {
    id: 3,
    category: "WEB APPLICATION",
    title: "Pokedex - View Stats and Abilities of Your Favorite Pokemon",
    image: "/images/pokeapp.png",
    demo: "https://pokemon-pokedex-demo.netlify.app/",
    github: "https://github.com/elliottcsipkes/pokemon-app",
    desc: "",
  },
  {
    id: 4,
    category: "WEB APPLICATION",
    title: "Notes - Write Custom Sticky Notes and Use Search to Filter Them",
    image: "./image/portfolio-04.jpg",
    demo: "https://sticky-notes-app-demo.netlify.app/",
    github: "https://github.com/elliottcsipkes/notes-app",
    desc: "",
  },
  {
    id: 5,
    category: "WEB APPLICATION",
    title: "Moviebase - Search For Information About Your Favorite Movies",
    image: "./image/portfolio-05.jpg",
    demo: "https://moviebase-demo.netlify.app/",
    github: "https://github.com/elliottcsipkes/movie-database-app",
    desc: "",
  },
  {
    id: 6,
    category: "PORTFOLIO WEBSITE",
    title: "Personal Portfolio - Learn More About My Projects and Experience",
    image: "/images/portfolio.png",
    demo: "",
    github: "https://github.com/elliottcsipkes/dev-porfolio",
    desc: "",
  },
];
export default Portfolio_data;
